version: 1.0.{build}
image: Visual Studio 2017
clone_script:
- cmd: git clone --recursive -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/dis-co/disco.git C:\projects\disco
environment:
  NODE_PATH: C:\Users\appveyor\AppData\Roaming\npm\node_modules
  APPVEYOR_CI_BUILD: true
  DISCO_TRACING: false
install:
- ps: >-
    netsh advfirewall set currentprofile state off


    Get-ExecutionPolicy -List

    Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force


    Install-Product node "6.9.2" x64


    npm --loglevel=error -g install npm@5.3.0

    node --version

    npm --version

    choco install git -r --no-progress

    choco install curl -r --no-progress

    choco install bonjour -r --no-progress

    cd dotnet

    $env:Path += ";$pwd\src\Lib"

    npm install --loglevel=error --no-optional

    Remove-Item alias:curl
cache:
- C:\projects\disco\flatbuffers-master\
- C:\Users\appveyor\AppData\Roaming\npm\node_modules\
build_script:
- ps: .\build.cmd Release
test_script:
- ps: .\build.cmd AllTests
artifacts:
- path: dotnet/Disco-*.zip
  name: Zipped Build
- path: dotnet/Disco.sha256sum
  name: Checksums
notifications:
- provider: Email
  to:
  - k@ioctl.it
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_finish:
- ps: >-
    .\build.cmd UploadArtifact

    Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }