version: 1.0.{build}
max_jobs: 4
image: Visual Studio 2015
environment:
  NODE_PATH: C:\Users\appveyor\AppData\Roaming\npm\node_modules
  APPVEYOR_CI_BUILD: true
install:
- ps: "netsh advfirewall set currentprofile state off\n\nGet-ExecutionPolicy -List\nSet-ExecutionPolicy -ExecutionPolicy Unrestricted -Force\n\n\nInstall-Product node \"6.9.2\" x64\nnpm --loglevel=error -g install npm\nchoco install cmake\nchoco install wget\nchoco install git\n\n$env:Path += \";C:\\Program Files\\CMake\\bin\"\n\nwget \"https://github.com/google/flatbuffers/archive/master.zip\" -o flatbuffers.zip\n7z x flatbuffers.zip\ncd flatbuffers-master\ncmake -Wno-dev -G \"Visual Studio 14 2015\"\nmsbuild flatc.vcxproj \n \n$env:Path += \";C:\\projects\\iris\\flatbuffers-master\\Debug\\\"\n\ncd ..\nnpm install --loglevel=error --no-optional"
cache:
- C:\Users\appveyor\AppData\Roaming\npm\node_modules
- C:/projects/iris/flatbuffers-master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.cmd Release
test_script:
- ps: .\build.cmd AllTests
artifacts:
- path: Iris-*.zip
  name: Zipped Build
- path: Iris.sha256sum
  name: Checksums
notifications:
- provider: Email
  to:
  - karsten@nsynk.de
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_finish:
- ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
cache:
  - packages -> paket.lock
  - node_modules -> package.json